[package]
name = "rustyqoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.10.0"
image = "0.24.2"

[features]
default = ["use_std"]
use_std = []
use_simd = []

[[bin]]
name = "rustyqoi"
path = "src/main.rs"
test = false
bench = false
doc = false

[lib]
name = "librustyqoi"
path = "src/qoi.rs"
test = false
bench = false
doc = false
crate-type = ["lib", "staticlib", "cdylib"]

