[package]
name = "rustyqoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"

[[bin]]
name = "rustyqoi"
path = "src/main.rs"
test = false
bench = false
doc = false
